export enum ERoutes {
    HOME = 'home',
    ADMIN = 'admin',
    ADMIN_UI_BUTTONS = 'button',
    ADMIN_UI_FORMS = 'forms',
    ADMIN_UI_CHECKBOX = 'checkbox',
    ADMIN_UI_RADIO = 'radio',
    ADMIN_UI_SELECT = 'select',
    ADMIN_UI_INPUT = 'input',
    ADMIN_UI_ICONS = 'icons',
    MENU = 'menu',
    QUIZ = 'quiz',
    LOREM_IPSUM = 'lorem-ipsum',
    COLOR_GENERATOR = 'color-generator',
    GROCERY_BUD = 'grocery-bud',
    CART = 'cart',
    HYRULE_JOBS = 'hyrule-jobs',
}